import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";

const read=path=>JSON.parse(fs.readFileSync(path,"utf8"));

const override=read("roadmap/pr20-9-craft-manual-development-override.json");
const roadmap=read("roadmap/post-r19-roadmap.json");
const merchant=read("grundlage/vertraege/runtime/merchant-remaining-production-preparation.json");
const preflight=read("grundlage/vertraege/runtime/pr21-merchant-integration-live-preflight.json");
const foundations=read("grundlage/vertraege/runtime/pr21-28-accelerated-foundations.json");
const historical=read("roadmap/pr20-9-craft-durable-shadow-no-candidate-evidence.json");

test("PR20.9 manual development override advances roadmap without inventing Craft evidence",()=>{
  assert.equal(override.status,"MANUAL_OVERRIDE_BESTANDEN_FOR_DEVELOPMENT");
  assert.equal(override.basis.kind,"OPERATOR_MANUAL_OVERRIDE");
  assert.equal(override.basis.liveCraftEvidenceProduced,false);
  assert.equal(override.basis.historicalNoCandidateEvidencePreserved,true);
  assert.equal(override.effects.countsAsPr20_9RoadmapRatification,true);
  assert.equal(override.effects.countsAsPr20CompletionForDevelopment,true);
  assert.equal(override.effects.unblocksPr21Development,true);
  assert.equal(override.effects.countsAsLiveCraftEvidence,false);
  assert.equal(override.effects.authorizesExternalRuntimeStart,false);
  assert.equal(override.effects.authorizesCraftMutation,false);
  assert.equal(override.authority.craftAuthority,false);
  assert.equal(override.authority.gameplayAuthority,false);
  assert.equal(override.authority.rawWriteAuthority,false);
  assert.equal(override.authority.broadGraphExecutionAuthority,false);
  assert.equal(override.authority.normalRuntimeAllowed,false);

  assert.equal(roadmap.currentStage,"PR21");
  assert.equal(roadmap.currentGate,"PR21_MERCHANT_INTEGRATION");
  assert.equal(roadmap.pr20_9.status,"MANUAL_OVERRIDE_BESTANDEN_FOR_DEVELOPMENT");
  assert.equal(roadmap.pr20_9.exitGate.satisfied,true);
  assert.equal(roadmap.pr20_9.exitGate.satisfiedByManualDevelopmentOverride,true);
  assert.equal(roadmap.pr20_9.exitGate.liveCraftEvidenceSatisfied,false);
  assert.equal(roadmap.pr20_9.manualDevelopmentOverride.status,"BESTANDEN_MANUELL");
  assert.equal(roadmap.pr20_9.productiveCraftAuthority,false);
  assert.equal(roadmap.pr20_9.gameplayAuthority,false);
  assert.equal(roadmap.pr20_9.rawWriteAuthority,false);
  assert.equal(roadmap.pr20_9.normalRuntimeAllowed,false);

  const pr20=roadmap.stages.find(x=>x.id==="PR20");
  const pr21=roadmap.stages.find(x=>x.id==="PR21");
  assert.equal(pr20?.status,"COMPLETE_MANUAL_OVERRIDE");
  assert.equal(pr21?.status,"IN_PROGRESS");
  assert.equal(roadmap.pr21.status,"REPOSITORY_STAGE_STATE_ONE_SHOT_EXECUTION_BOUNDARY_PREPARED");
  assert.deepEqual(roadmap.pr21.blockedBy,[]);
  assert.equal(roadmap.pr21.liveExecutionAllowed,false);
  assert.equal(roadmap.pr21.livePreflight.manualPr20_9OverrideAccepted,true);
  assert.deepEqual(roadmap.pr21.livePreflight.missingRatifications,[]);
  assert.equal(roadmap.pr21.livePreflight.externalRuntimeStartAuthorized,false);
  assert.equal(roadmap.pr21.observerHandoff.status,"PREPARED_NO_WRITE_NO_START_AUTHORITY");
  assert.equal(roadmap.pr21.observerHandoff.externalRuntimeStartAuthorized,false);
  assert.equal(roadmap.pr21.sampleCollector.status,"PREPARED_NO_WRITE_NO_START_AUTHORITY");
  assert.equal(roadmap.pr21.sampleCollector.externalRuntimeStartAuthorized,false);
  assert.equal(roadmap.pr21.freezeEvaluationHandoff.status,"PREPARED_NO_WRITE_NO_AUTO_RATIFICATION");
  assert.equal(roadmap.pr21.freezeEvaluationHandoff.automaticRatification,false);
  assert.equal(roadmap.pr21.ratificationRecordBoundary.status,"PREPARED_EXPLICIT_CONFIRMATION_ONLY");
  assert.equal(roadmap.pr21.ratificationRecordBoundary.gateAdvanced,false);
  assert.equal(roadmap.pr21.gateProposalBoundary.status,"PREPARED_PROPOSAL_ONLY_DEFAULT_OFF");
  assert.equal(roadmap.pr21.gateProposalBoundary.gateMutationPerformed,false);
  assert.equal(roadmap.pr21.defaultOffApplyBoundary.status,"PREPARED_DEFAULT_OFF_NO_EXECUTION");
  assert.equal(roadmap.pr21.defaultOffApplyBoundary.executionEnabled,false);
  assert.equal(roadmap.pr21.applyExecutionAuthorizationBoundary.status,"PREPARED_EXPLICIT_ONE_SHOT_AUTHORIZATION_NO_EXECUTION");
  assert.equal(roadmap.pr21.oneShotGateApplyExecutionBoundary.status,"PREPARED_ONE_SHOT_CONTROL_PLANE_EXECUTION");
  assert.equal(roadmap.pr21.oneShotGateApplyExecutionBoundary.pr22Activated,false);
  assert.equal(roadmap.pr21.postSettlementTransitionBoundary.status,"PREPARED_POST_SETTLEMENT_TRANSITION_PROPOSAL_ONLY");
  assert.equal(roadmap.pr21.postSettlementTransitionBoundary.pr21StageCompletionApplied,false);
  assert.equal(roadmap.pr21.postSettlementTransitionBoundary.pr22DevelopmentStageActivated,false);
  assert.equal(roadmap.pr21.postSettlementTransitionBoundary.pr22ProductiveAuthorityIssued,false);
  assert.equal(roadmap.pr21.stageCompletionApplyBoundary.status,"PREPARED_STAGE_COMPLETION_DEFAULT_OFF_NO_EXECUTION");
  assert.equal(roadmap.pr21.stageCompletionApplyBoundary.executionEnabled,false);
  assert.equal(roadmap.pr21.stageCompletionApplyBoundary.pr21StageCompletionApplied,false);
  assert.equal(roadmap.pr21.stageCompletionApplyBoundary.pr22DevelopmentStageActivated,false);
  assert.equal(roadmap.pr21.stageCompletionExecutionAuthorizationBoundary.status,"PREPARED_EXPLICIT_STAGE_COMPLETION_ONE_SHOT_AUTHORIZATION_NO_EXECUTION");
  assert.equal(roadmap.pr21.stageCompletionExecutionAuthorizationBoundary.executionEnabled,false);
  assert.equal(roadmap.pr21.stageCompletionExecutionAuthorizationBoundary.pr21StageCompletionApplied,false);
  assert.equal(roadmap.pr21.stageCompletionExecutionAuthorizationBoundary.pr22DevelopmentStageActivated,false);
  assert.equal(roadmap.pr21.stageCompletionOneShotExecutionBoundary.status,"PREPARED_ONE_SHOT_STAGE_COMPLETION_CONTROL_PLANE_EXECUTION");
  assert.equal(roadmap.pr21.stageCompletionOneShotExecutionBoundary.executionPerformed,false);
  assert.equal(roadmap.pr21.stageCompletionOneShotExecutionBoundary.pr21StageCompletionApplied,false);
  assert.equal(roadmap.pr21.stageCompletionOneShotExecutionBoundary.pr22DevelopmentStageActivated,false);
  assert.equal(roadmap.pr21.stageCompletionOneShotExecutionBoundary.pr22ProductiveAuthorityIssued,false);
  assert.equal(roadmap.pr21.stageCompletionPostExecutionTransitionBoundary.status,"PREPARED_POST_EXECUTION_REPOSITORY_TRANSITION_PROPOSAL_ONLY");
  assert.equal(roadmap.pr21.stageCompletionPostExecutionTransitionBoundary.repositoryStageStateApplied,false);
  assert.equal(roadmap.pr21.stageCompletionPostExecutionTransitionBoundary.roadmapMutationPerformed,false);
  assert.equal(roadmap.pr21.stageCompletionPostExecutionTransitionBoundary.pr22ProductiveAuthorityIssued,false);
  assert.equal(roadmap.pr21.repositoryStageStateApplyBoundary.status,"PREPARED_REPOSITORY_STAGE_STATE_DEFAULT_OFF_NO_EXECUTION");
  assert.equal(roadmap.pr21.repositoryStageStateApplyBoundary.executionEnabled,false);
  assert.equal(roadmap.pr21.repositoryStageStateApplyBoundary.repositoryStageStateApplied,false);
  assert.equal(roadmap.pr21.repositoryStageStateApplyBoundary.targetCurrentStage,"PR22");
  assert.equal(roadmap.pr21.repositoryStageStateApplyBoundary.targetCurrentGate,"PR22_MULTI_CHARACTER_COORDINATION");
  assert.equal(roadmap.pr21.repositoryStageStateExecutionAuthorizationBoundary.status,"PREPARED_EXPLICIT_REPOSITORY_STAGE_STATE_ONE_SHOT_AUTHORIZATION_NO_EXECUTION");
  assert.equal(roadmap.pr21.repositoryStageStateExecutionAuthorizationBoundary.executionEnabled,false);
  assert.equal(roadmap.pr21.repositoryStageStateExecutionAuthorizationBoundary.repositoryStageStateApplied,false);
  assert.equal(roadmap.pr21.repositoryStageStateExecutionAuthorizationBoundary.pr22ProductiveAuthorityIssued,false);
  assert.equal(roadmap.pr21.repositoryStageStateOneShotExecutionBoundary.status,"PREPARED_ONE_SHOT_REPOSITORY_STAGE_STATE_EXECUTION");
  assert.equal(roadmap.pr21.repositoryStageStateOneShotExecutionBoundary.executionPerformed,false);
  assert.equal(roadmap.pr21.repositoryStageStateOneShotExecutionBoundary.repositoryStageStateApplied,false);
  assert.equal(roadmap.pr21.repositoryStageStateOneShotExecutionBoundary.currentStage,"PR21");
  assert.equal(roadmap.pr21.repositoryStageStateOneShotExecutionBoundary.pr22StageStatus,"BLOCKED_BY_PR21");
  assert.equal(roadmap.pr21.applyExecutionAuthorizationBoundary.executionEnabled,false);
});

test("historical PR20.9 no-candidate evidence remains unchanged in meaning",()=>{
  assert.equal(historical.status,"RATIFIED_BLOCKED_NO_NORMAL_CANDIDATE_ZERO_WRITE");
  assert.equal(historical.testId,"pr20-9-craft-durable-shadow-no-write");
  assert.equal(historical.terminalStatus,"BLOCKIERT");
  assert.equal(historical.blocker,"PR20_9_CRAFT_SHADOW_KEIN_NORMALKANDIDAT");
  assert.equal(historical.conclusion.craftRatified,false);
  assert.equal(historical.conclusion.productiveCraftAuthorityOpened,false);
  assert.equal(historical.conclusion.candidateAcquisitionOrMutationAllowed,false);
  assert.equal(historical.safety.gameplayWrites,0);
  assert.equal(historical.safety.publicFunctionCalls,0);
  assert.equal(historical.safety.rawWriteCalls,0);
  assert.equal(historical.safety.normalRuntimeAllowed,false);
});

test("Merchant and PR21 contracts accept only the development override, never runtime authority",()=>{
  assert.equal(merchant.pr20_9.status,"MANUAL_OVERRIDE_BESTANDEN_FOR_DEVELOPMENT");
  assert.equal(merchant.pr20_9.manualDevelopmentOverride.liveCraftEvidenceProduced,false);
  assert.equal(merchant.pr21.status,"AKTIV_FUER_WEITERENTWICKLUNG_NO_WRITE");
  assert.equal(merchant.pr21.manualPr20_9Override.accepted,true);

  assert.equal(preflight.status,"PREPARED_NO_WRITE_MANUAL_PR20_9_OVERRIDE");
  assert.deepEqual(preflight.currentRepositoryState.missingRatifications,[]);
  assert.equal(preflight.currentRepositoryState.manualPr20_9OverrideAccepted,true);
  assert.equal(preflight.currentRepositoryState.liveCraftEvidenceSatisfied,false);
  assert.equal(preflight.currentRepositoryState.externalRuntimeStartAuthorized,false);
  assert.equal(preflight.safety.manualDevelopmentRatificationCredit,true);
  assert.equal(preflight.safety.currentPr20_9RatificationCredit,false);
  assert.equal(preflight.safety.gameplayAuthority,false);
  assert.equal(preflight.safety.rawWriteAuthority,false);
  assert.equal(preflight.safety.normalRuntimeAllowed,false);

  assert.equal(
    foundations.stages.pr21.status,
    "REPOSITORY_STAGE_STATE_ONE_SHOT_EXECUTION_BOUNDARY_PREPARED",
  );
  assert.equal(foundations.stages.pr21.livePreflight.manualPr20_9OverrideAccepted,true);
  assert.deepEqual(foundations.stages.pr21.livePreflight.currentMissingRatifications,[]);
  assert.equal(foundations.stages.pr21.livePreflight.externalRuntimeStartAuthorized,false);
  assert.equal(foundations.stages.pr21.observerHandoff.status,"PREPARED_NO_WRITE_NO_START_AUTHORITY");
  assert.equal(foundations.stages.pr21.observerHandoff.externalRuntimeStartAuthorized,false);
  assert.equal(foundations.stages.pr21.sampleCollector.status,"PREPARED_NO_WRITE_NO_START_AUTHORITY");
  assert.equal(foundations.stages.pr21.sampleCollector.externalRuntimeStartAuthorized,false);
  assert.equal(foundations.stages.pr21.freezeEvaluationHandoff.status,"PREPARED_NO_WRITE_NO_AUTO_RATIFICATION");
  assert.equal(foundations.stages.pr21.freezeEvaluationHandoff.automaticRatification,false);
  assert.equal(foundations.stages.pr21.ratificationRecordBoundary.status,"PREPARED_EXPLICIT_CONFIRMATION_ONLY");
  assert.equal(foundations.stages.pr21.ratificationRecordBoundary.gateAdvanced,false);
  assert.equal(foundations.stages.pr21.gateProposalBoundary.status,"PREPARED_PROPOSAL_ONLY_DEFAULT_OFF");
  assert.equal(foundations.stages.pr21.gateProposalBoundary.gateMutationPerformed,false);
  assert.equal(foundations.stages.pr21.defaultOffApplyBoundary.status,"PREPARED_DEFAULT_OFF_NO_EXECUTION");
  assert.equal(foundations.stages.pr21.defaultOffApplyBoundary.executionEnabled,false);
  assert.equal(foundations.stages.pr21.applyExecutionAuthorizationBoundary.status,"PREPARED_EXPLICIT_ONE_SHOT_AUTHORIZATION_NO_EXECUTION");
  assert.equal(foundations.stages.pr21.oneShotGateApplyExecutionBoundary.status,"PREPARED_ONE_SHOT_CONTROL_PLANE_EXECUTION");
  assert.equal(foundations.stages.pr21.oneShotGateApplyExecutionBoundary.pr22Activated,false);
  assert.equal(foundations.stages.pr21.postSettlementTransitionBoundary.status,"PREPARED_POST_SETTLEMENT_TRANSITION_PROPOSAL_ONLY");
  assert.equal(foundations.stages.pr21.postSettlementTransitionBoundary.pr21StageCompletionApplied,false);
  assert.equal(foundations.stages.pr21.postSettlementTransitionBoundary.pr22DevelopmentStageActivated,false);
  assert.equal(foundations.stages.pr21.postSettlementTransitionBoundary.pr22ProductiveAuthorityIssued,false);
  assert.equal(foundations.stages.pr21.stageCompletionApplyBoundary.status,"PREPARED_STAGE_COMPLETION_DEFAULT_OFF_NO_EXECUTION");
  assert.equal(foundations.stages.pr21.stageCompletionApplyBoundary.executionEnabled,false);
  assert.equal(foundations.stages.pr21.stageCompletionApplyBoundary.pr21StageCompletionApplied,false);
  assert.equal(foundations.stages.pr21.stageCompletionApplyBoundary.pr22DevelopmentStageActivated,false);
  assert.equal(foundations.stages.pr21.stageCompletionExecutionAuthorizationBoundary.status,"PREPARED_EXPLICIT_STAGE_COMPLETION_ONE_SHOT_AUTHORIZATION_NO_EXECUTION");
  assert.equal(foundations.stages.pr21.stageCompletionExecutionAuthorizationBoundary.executionEnabled,false);
  assert.equal(foundations.stages.pr21.stageCompletionExecutionAuthorizationBoundary.pr21StageCompletionApplied,false);
  assert.equal(foundations.stages.pr21.stageCompletionExecutionAuthorizationBoundary.pr22DevelopmentStageActivated,false);
  assert.equal(foundations.stages.pr21.stageCompletionOneShotExecutionBoundary.status,"PREPARED_ONE_SHOT_STAGE_COMPLETION_CONTROL_PLANE_EXECUTION");
  assert.equal(foundations.stages.pr21.stageCompletionOneShotExecutionBoundary.executionPerformed,false);
  assert.equal(foundations.stages.pr21.stageCompletionOneShotExecutionBoundary.pr21StageCompletionApplied,false);
  assert.equal(foundations.stages.pr21.stageCompletionOneShotExecutionBoundary.pr22DevelopmentStageActivated,false);
  assert.equal(foundations.stages.pr21.stageCompletionOneShotExecutionBoundary.pr22ProductiveAuthorityIssued,false);
  assert.equal(foundations.stages.pr21.stageCompletionPostExecutionTransitionBoundary.status,"PREPARED_POST_EXECUTION_REPOSITORY_TRANSITION_PROPOSAL_ONLY");
  assert.equal(foundations.stages.pr21.stageCompletionPostExecutionTransitionBoundary.repositoryStageStateApplied,false);
  assert.equal(foundations.stages.pr21.stageCompletionPostExecutionTransitionBoundary.roadmapMutationPerformed,false);
  assert.equal(foundations.stages.pr21.stageCompletionPostExecutionTransitionBoundary.pr22ProductiveAuthorityIssued,false);
  assert.equal(foundations.stages.pr21.repositoryStageStateApplyBoundary.status,"PREPARED_REPOSITORY_STAGE_STATE_DEFAULT_OFF_NO_EXECUTION");
  assert.equal(foundations.stages.pr21.repositoryStageStateApplyBoundary.executionEnabled,false);
  assert.equal(foundations.stages.pr21.repositoryStageStateApplyBoundary.repositoryStageStateApplied,false);
  assert.equal(foundations.stages.pr21.repositoryStageStateApplyBoundary.targetCurrentStage,"PR22");
  assert.equal(foundations.stages.pr21.repositoryStageStateApplyBoundary.targetCurrentGate,"PR22_MULTI_CHARACTER_COORDINATION");
  assert.equal(foundations.stages.pr21.repositoryStageStateExecutionAuthorizationBoundary.status,"PREPARED_EXPLICIT_REPOSITORY_STAGE_STATE_ONE_SHOT_AUTHORIZATION_NO_EXECUTION");
  assert.equal(foundations.stages.pr21.repositoryStageStateExecutionAuthorizationBoundary.executionEnabled,false);
  assert.equal(foundations.stages.pr21.repositoryStageStateExecutionAuthorizationBoundary.repositoryStageStateApplied,false);
  assert.equal(foundations.stages.pr21.repositoryStageStateExecutionAuthorizationBoundary.pr22ProductiveAuthorityIssued,false);
  assert.equal(foundations.stages.pr21.repositoryStageStateOneShotExecutionBoundary.status,"PREPARED_ONE_SHOT_REPOSITORY_STAGE_STATE_EXECUTION");
  assert.equal(foundations.stages.pr21.repositoryStageStateOneShotExecutionBoundary.executionPerformed,false);
  assert.equal(foundations.stages.pr21.repositoryStageStateOneShotExecutionBoundary.repositoryStageStateApplied,false);
  assert.equal(foundations.stages.pr21.repositoryStageStateOneShotExecutionBoundary.currentStage,"PR21");
  assert.equal(foundations.stages.pr21.repositoryStageStateOneShotExecutionBoundary.pr22StageStatus,"BLOCKED_BY_PR21");
  assert.equal(foundations.stages.pr21.applyExecutionAuthorizationBoundary.executionEnabled,false);
});
