from pathlib import Path
import json, re
root=Path('/mnt/data/aio214prep')
bot_path=root/'bot.js'
s=bot_path.read_text()
# Version bump
s=s.replace('AiO Bot 2.13.0 | 2026-09-10','AiO Bot 2.14.0 | 2026-09-10',1)
s=s.replace("var VERSION = '2.13.0';","var VERSION = '2.14.0';",1)
# defaults
old="""    brainQualityMonitorEnabled: true, brainQualityWindow: 24, brainQualityMinOutcomes: 12, brainQualityOverconfidencePct: 88, brainQualityRewardDropPct: 15, brainQualityCooldownMinutes: 20,\n    cloudSyncEnabled: true, cloudSyncSeconds: 45, farmerUpgradeCheckSeconds: 90, merchantExploreWhenIdle: true,"""
new="""    brainQualityMonitorEnabled: true, brainQualityWindow: 24, brainQualityMinOutcomes: 12, brainQualityOverconfidencePct: 88, brainQualityRewardDropPct: 15, brainQualityCooldownMinutes: 20,\n    brainResearchBridgeEnabled: true, brainResearchProfile: 'development', brainResearchHours: 24, brainResearchMaxHighlights: 20, brainResearchAnonymize: true,\n    cloudSyncEnabled: true, cloudSyncSeconds: 45, farmerUpgradeCheckSeconds: 90, merchantExploreWhenIdle: true,"""
assert old in s
s=s.replace(old,new,1)
# clean config append before cloud sync cleanup
old="out.brainQualityCooldownMinutes=clamp(out.brainQualityCooldownMinutes,5,120); out.cloudSyncEnabled=out.cloudSyncEnabled!==false;"
new="out.brainQualityCooldownMinutes=clamp(out.brainQualityCooldownMinutes,5,120); out.brainResearchBridgeEnabled=out.brainResearchBridgeEnabled!==false; out.brainResearchProfile=['overall','errors','learning','farm','merchant','development'].indexOf(String(out.brainResearchProfile))>=0?String(out.brainResearchProfile):'development'; out.brainResearchHours=clamp(out.brainResearchHours,1,168); out.brainResearchMaxHighlights=clamp(out.brainResearchMaxHighlights,5,40); out.brainResearchAnonymize=out.brainResearchAnonymize!==false; out.cloudSyncEnabled=out.cloudSyncEnabled!==false;"
assert old in s
s=s.replace(old,new,1)
# feature contract
old="'brain-quality-monitor','brain-overconfidence-guard','brain-drift-quarantine','adaptive-learning-control'"
new="'brain-quality-monitor','brain-overconfidence-guard','brain-drift-quarantine','adaptive-learning-control','brain-research-bridge','research-prompt-profiles','research-secret-redaction','research-dashboard'"
assert old in s
s=s.replace(old,new,1)
# insert research section
marker="""  var v210DashboardBase=dashboardPayload;\n  dashboardPayload=function(){var d=v210DashboardBase();d.version=9;d.brain=v210BrainTelemetry();return d;};\n  audit('feature_contract','2.13.0 Brain-v2 Kernfunktionen geprüft',{features:FEATURE_CONTRACT,student:{inputs:V210_INPUTS,hidden:V210_HIDDEN,outputs:V210_OUTPUTS},configHash:v282ConfigHash(C)});"""
assert marker in s
research=r'''  // ---------------------------------------------------------------------------
  // 2.14.0 AiO Research Bridge · compact, redacted prompts for higher-level review
  // ---------------------------------------------------------------------------
  var V214_RESEARCH_PROFILES={
    overall:{label:'Gesamtanalyse',task:'Bewerte den Gesamtzustand des AiO-Bots. Suche nach den wichtigsten Hebeln für 24/7-Stabilität, EXP/h, Gold/h, Lernqualität und Wartbarkeit.'},
    errors:{label:'Fehleranalyse',task:'Analysiere wiederkehrende Fehler, Loops, Blockaden und Sicherheitsprobleme. Priorisiere konkrete Root Causes und robuste Code-Fixes.'},
    learning:{label:'Lernanalyse',task:'Analysiere Student, Teacher, Champion/Challenger, Rewards, Kalibrierung und Lernqualität. Finde Falschlernen, Datenlücken und bessere Lernsignale.'},
    farm:{label:'Farmanalyse',task:'Analysiere Farmziele, Zonen, Monster, Konkurrenz, EXP/h, Gold/h und Sicherheit. Schlage datenbegründete Verbesserungen der Farmstrategie vor.'},
    merchant:{label:'Merchant-Analyse',task:'Analysiere Inventardruck, Versorgung, Bank, Upgrade/Compound, Verkauf, Wege und Merchant-Fehler. Suche nach 24/7-tauglichen Optimierungen.'},
    development:{label:'Entwicklungsbrief',task:'Leite konkrete Änderungen für die nächste AiO-Bot-Version ab. Trenne deterministische Codeänderungen von Änderungen am neuronalen Brain und priorisiere nach Nutzen, Risiko und Testbarkeit.'}
  };
  function v214ResearchProfile(id){id=String(id||C.brainResearchProfile||'development');return V214_RESEARCH_PROFILES[id]?id:'development';}
  function v214ResearchAliases(anonymize){var map={},farmer=0,merchant=0;ACCOUNT_CHARS.forEach(function(c){var n=String(c.name||'');if(!n)return;if(!anonymize){map[n]=n;return;}if(String(c.ctype||'')==='merchant'){merchant++;map[n]=merchant===1?'Merchant':'Merchant'+merchant;}else{farmer++;map[n]='Farmer'+farmer;}});if(!map[me])map[me]=anonymize?(character.ctype==='merchant'?'Merchant':'Farmer'+(farmer+1)):me;return map;}
  function v214ResearchSafeText(value,aliases){var x=safeString(value==null?'':value,1800),secrets=[C.webDashboardWriteKey].filter(Boolean);secrets.forEach(function(sec){sec=String(sec);if(sec.length>=4)x=x.split(sec).join('[REDACTED]');});x=x.replace(/\b(WRITE_KEY|READ_KEY|API[_-]?KEY|TOKEN|SECRET|AUTHORIZATION)\b\s*[:=]\s*[^\s,;]+/ig,'$1=[REDACTED]');Object.keys(aliases||{}).sort(function(a,b){return b.length-a.length;}).forEach(function(name){if(name&&aliases[name]!==name)x=x.split(name).join(aliases[name]);});return x;}
  function v214ResearchAuditErrors(cutoff,aliases,profile){var rows=(S.auditRecent||[]).filter(function(e){if(!e||Number(e.at||0)<cutoff)return false;var k=String(e.kind||''),lv=String(e.level||'');if(profile==='merchant'&&!/merchant|inventory|bank|upgrade|compound|scroll|sell|buy|action_error/i.test(k+' '+String(e.message||'')))return false;return lv==='error'||lv==='critical'||lv==='warning'||/error|fail|cant_space|inventory_full|rollback|quarantine/i.test(k+' '+String(e.message||''));}),groups={};rows.forEach(function(e){var msg=v214ResearchSafeText(e.message||e.kind,aliases),cls=v214ResearchSafeText(e.data&&(e.data.errorClass||e.data.error)||'',aliases),key=String(e.kind||'event')+'|'+msg+'|'+cls,g=groups[key]||(groups[key]={kind:String(e.kind||'event'),message:msg,errorClass:cls,count:0,lastAt:0,level:String(e.level||'warning')});g.count++;g.lastAt=Math.max(g.lastAt,Number(e.at)||0);});return Object.keys(groups).map(function(k){return groups[k];}).sort(function(a,b){return b.count-a.count||b.lastAt-a.lastAt;}).slice(0,12);}
  function v214ResearchLearning(aliases){var ld=v290CompactLearning(),mons=Object.keys(ld.monsters||{}).map(function(id){var m=ld.monsters[id]||{};return {monster:v214ResearchSafeText(id,aliases),kills:Number(m.kills)||0,lootEvents:Number(m.lootEvents)||0,gold:Number(m.gold)||0,lastAt:Number(m.lastAt)||0};}).sort(function(a,b){return b.kills-a.kills||b.lootEvents-a.lootEvents;}).slice(0,12),zones=Object.keys(ld.zones||{}).map(function(k){var z=ld.zones[k]||{};return {zone:v214ResearchSafeText(k,aliases),samples:Number(z.samples)||0,xpPerHour:Number(z.xpPerHour||z.avgXpPerHour||z.xp)||0,goldPerHour:Number(z.goldPerHour||z.avgGoldPerHour||z.gold)||0,safetyPct:Number(z.safetyPct||z.safety)||0,lastAt:Number(z.lastAt||z.updatedAt)||0};}).sort(function(a,b){return b.samples-a.samples;}).slice(0,12);return {updatedAt:Number(ld.updatedAt)||0,monsters:mons,zones:zones};}
  function v214ResearchHighlights(cutoff,aliases,profile){var weights={rollback:9,error:8,quality_quarantine:8,quality_degraded:7,reject:6,promotion:6,teacher:3,outcome:3,challenge:4,confirmed:4,quality_watch:4,day_summary:2},rows=(S.brainDiary||[]).filter(function(e){return e&&Number(e.at||0)>=cutoff;}).map(function(e){var reward=e.reward==null?0:Number(e.reward)||0,score=(weights[String(e.kind||'')]||1)+Math.abs(reward)*8;if(profile==='learning'&&/teacher|outcome|challenge|promotion|rollback|quality/.test(String(e.kind)))score+=4;if(profile==='errors'&&(e.tone==='bad'||e.tone==='warn'))score+=5;if(profile==='farm'&&/farm|xp|monster|zone/i.test(String(e.title||'')+' '+String(e.detail||'')))score+=5;if(profile==='merchant'&&/merchant|inventory|compound|upgrade|bank|sell|scroll/i.test(String(e.title||'')+' '+String(e.detail||'')))score+=5;return {at:Number(e.at)||0,kind:String(e.kind||''),title:v214ResearchSafeText(e.title,aliases),detail:v214ResearchSafeText(e.detail,aliases),action:String(e.action||''),target:v214ResearchSafeText(e.target,aliases),reward:e.reward==null?null:v210Round(reward,4),generation:Number(e.generation)||0,score:score};}).sort(function(a,b){return b.score-a.score||b.at-a.at;});return rows.slice(0,Number(C.brainResearchMaxHighlights)||20);}
  function v214ResearchRates(){var r=v273RateStats(),f=S.farmHealth||{},ps=partyState();return {xpPerHour:Number(r.xpPerHour)||0,goldPerHour:Number(r.goldPerHour)||0,xpGain:Number(r.xpGain)||0,goldGain:Number(r.goldGain)||0,freeSlots:freeSlots(),inventorySlots:(character.items||[]).length||0,farmSafetyPct:Number(f.safetyPct)||0,visibleMonsters:Number(f.visible)||0,competitors:Number(f.competitors)||0,partyComplete:!!ps.complete};}
  function v214ResearchData(profile,hours,anonymize){profile=v214ResearchProfile(profile);hours=clamp(Number(hours)||Number(C.brainResearchHours)||24,1,168);anonymize=anonymize!==false;var aliases=v214ResearchAliases(anonymize),cutoff=clock()-hours*3600000,t=v210BrainTelemetry(),q=v213QualitySummary(),l=v211LeagueSummary(),ps=partyState(),learning=v214ResearchLearning(aliases),errors=v214ResearchAuditErrors(cutoff,aliases,profile),highlights=v214ResearchHighlights(cutoff,aliases,profile),lessons=(S.brainDiary||[]).filter(function(e){return e&&e.kind==='teacher'&&Number(e.at||0)>=cutoff;}).slice(-12).reverse().map(function(e){return {at:Number(e.at)||0,title:v214ResearchSafeText(e.title,aliases),lesson:v214ResearchSafeText(e.detail,aliases),action:String(e.action||''),target:v214ResearchSafeText(e.target,aliases)};}),outcomes=(S.brainDiary||[]).filter(function(e){return e&&e.kind==='outcome'&&Number(e.at||0)>=cutoff&&e.reward!=null;}).sort(function(a,b){return Math.abs(Number(b.reward)||0)-Math.abs(Number(a.reward)||0);}).slice(0,12).map(function(e){return {at:Number(e.at)||0,title:v214ResearchSafeText(e.title,aliases),detail:v214ResearchSafeText(e.detail,aliases),reward:v210Round(Number(e.reward)||0,4),action:String(e.action||''),target:v214ResearchSafeText(e.target,aliases)};});return {schema:1,source:'local-bot',profile:profile,profileLabel:V214_RESEARCH_PROFILES[profile].label,generatedAt:clock(),windowHours:hours,anonymized:anonymize,bot:{version:VERSION,build:BUILD,character:aliases[me]||me,ctype:String(character.ctype||''),level:Number(character.level)||0,map:v214ResearchSafeText(character.map,aliases)},party:{members:(ps.members||[]).map(function(n){return aliases[n]||v214ResearchSafeText(n,aliases);}),missing:(ps.missing||[]).map(function(n){return aliases[n]||v214ResearchSafeText(n,aliases);}),complete:!!ps.complete},performance:v214ResearchRates(),brain:{usedToday:Number(t.usedToday)||0,limit:Number(t.limit)||10000,target:Number(t.target)||0,teacherRequests:Number(t.teacherRequests)||0,avgNeurons:Number(t.avgNeurons)||0,outcomes:Number(t.outcomes)||0,student:t.student||{},quality:q,league:l},current:{status:v214ResearchSafeText(S.status,aliases),mode:v214ResearchSafeText(S.mode,aliases),goal:S.goal?{map:v214ResearchSafeText(S.goal.map,aliases),monster:v214ResearchSafeText(S.goal.monster,aliases)}:null,merchantPlan:profile==='farm'?null:(S.merchantPlan?{steps:(S.merchantPlan.steps||[]).slice(0,6).map(function(x){return v214ResearchSafeText(x,aliases);}),farmOrder:S.merchantPlan.farmOrder||null}:null)},repeatedErrors:errors,highlights:highlights,teacherLessons:lessons,strongestOutcomes:outcomes,learning:(profile==='errors'?{updatedAt:learning.updatedAt,monsters:[],zones:[]}:learning),dataLimitations:['Lokale Audit-Historie ist auf die im laufenden Client gehaltenen Ereignisse begrenzt.','Keine vollständigen neuronalen Gewichtsmatrizen exportiert.','Keine Secrets, WRITE_KEY/READ_KEY oder Auth-Tokens exportiert.']};}
  function v214ResearchPrompt(profile,hours,anonymize){var data=v214ResearchData(profile,hours,anonymize),spec=V214_RESEARCH_PROFILES[data.profile],json='';try{json=JSON.stringify(data,null,2);}catch(e){json='{}';}return 'AiO Research Bridge · '+spec.label+'\n\n'+spec.task+'\n\nArbeitsregeln für die Analyse:\n- Nutze nur die gelieferten Daten als Tatsachengrundlage und markiere Unsicherheit/Datenlücken.\n- Priorisiere 24/7-Stabilität und Sicherheit vor EXP/h und Gold/h.\n- Trenne konkrete Änderungen am deterministischen Bot-Code von Änderungen am neuronalen Brain.\n- Nenne bei jeder Empfehlung erwarteten Nutzen, Risiko und einen prüfbaren Test.\n- Suche besonders nach wiederkehrenden Fehlern, Reward-Verschlechterung, Overconfidence, unnötigen Teacher-Aufrufen und Merchant-/Inventar-Loops.\n- Wenn bestehende Logik bereits korrekt reagiert, schlage keine Änderung nur um der Änderung willen vor.\n\nStrukturierte Bot-Daten:\n```json\n'+json+'\n```\n\nBitte liefere eine priorisierte technische Analyse und – wenn sinnvoll – einen konkreten Plan für die nächste Bot-Version.';}
  function v214ResearchSummary(){var d=v214ResearchData(C.brainResearchProfile,C.brainResearchHours,C.brainResearchAnonymize),q=d.brain.quality||{};return {schema:1,profile:d.profile,profileLabel:d.profileLabel,generatedAt:d.generatedAt,windowHours:d.windowHours,anonymized:d.anonymized,quality:{status:q.status,score:q.score,recentReward:q.recentReward,overconfidenceFailureRate:q.overconfidenceFailureRate},repeatedErrors:d.repeatedErrors.slice(0,8),highlights:d.highlights.slice(0,10),teacherLessons:d.teacherLessons.slice(0,8),strongestOutcomes:d.strongestOutcomes.slice(0,8),performance:d.performance,learning:{monsters:d.learning.monsters.slice(0,8),zones:d.learning.zones.slice(0,8)}};}
  function v214ResearchShow(profile){var text=v214ResearchPrompt(profile,C.brainResearchHours,C.brainResearchAnonymize);if(HEADLESS){gameMessage('Research Brief erzeugt · '+text.length+' Zeichen','#63e1bd');return text;}var el=D.createElement('div');el.className='overlay research-bridge-modal';el.innerHTML='<div class="modal"><div class="modaltop"><h2>🔬 AiO Research Bridge</h2><button class="close" data-action="modal-close">×</button></div><div class="notice">Der Prompt enthält nur ausgewählte Telemetrie. Secrets werden entfernt'+(C.brainResearchAnonymize?' und Charakternamen anonymisiert':'')+'.</div><textarea class="research-prompt" readonly>'+esc(text)+'</textarea><div class="buttons"><button class="btn primary" data-action="research-copy" data-profile="'+esc(v214ResearchProfile(profile))+'">Prompt kopieren</button></div></div>';uiRoot.appendChild(el);P.setTimeout(function(){var ta=el.querySelector('.research-prompt');if(ta){ta.focus();ta.select();}},30);return text;}
  function v214ResearchCopy(profile){var text=v214ResearchPrompt(profile,C.brainResearchHours,C.brainResearchAnonymize),nav=P.navigator||{},done=function(){audit('brain_research_copy','Research-Prompt erzeugt/kopiert',{profile:v214ResearchProfile(profile),hours:C.brainResearchHours,chars:text.length,anonymized:!!C.brainResearchAnonymize});gameMessage('AiO Research Prompt kopiert · '+V214_RESEARCH_PROFILES[v214ResearchProfile(profile)].label,'#63e1bd');};try{if(nav.clipboard&&typeof nav.clipboard.writeText==='function'){Promise.resolve(nav.clipboard.writeText(text)).then(done).catch(function(){v214ResearchShow(profile);});return text;}}catch(e){}v214ResearchShow(profile);return text;}
  var v214StudentExportBase=v210StudentExport;
  v210StudentExport=function(){var x=v214StudentExportBase();if(C.brainResearchBridgeEnabled){x.research={schema:1,summary:v214ResearchSummary(),updatedAt:clock()};x.telemetry=x.telemetry||{};x.telemetry.research={enabled:true,profile:C.brainResearchProfile,windowHours:C.brainResearchHours,anonymized:!!C.brainResearchAnonymize,updatedAt:clock()};}return x;};
  var v214TelemetryBase=v210BrainTelemetry;
  v210BrainTelemetry=function(){var x=v214TelemetryBase();x.research={enabled:!!C.brainResearchBridgeEnabled,profile:v214ResearchProfile(C.brainResearchProfile),profileLabel:V214_RESEARCH_PROFILES[v214ResearchProfile(C.brainResearchProfile)].label,windowHours:Number(C.brainResearchHours)||24,anonymized:!!C.brainResearchAnonymize,highlights:C.brainResearchBridgeEnabled?v214ResearchHighlights(clock()-(Number(C.brainResearchHours)||24)*3600000,v214ResearchAliases(C.brainResearchAnonymize),C.brainResearchProfile).slice(0,4):[]};return x;};
  var v214BrainHTMLBase=v290BrainHTML;
  v290BrainHTML=function(){var base=v214BrainHTMLBase(),p=v214ResearchProfile(C.brainResearchProfile),summary=C.brainResearchBridgeEnabled?v214ResearchSummary():null;return base+'<div class="card research-bridge-card"><h3>🔬 AiO Research Bridge</h3><div class="muted">Verdichtet echte Lernerfahrung zu einem Prompt für eine übergeordnete ChatGPT-Analyse. Kein zusätzlicher Teacher-Aufruf und keine zusätzlichen Workers-AI-Neurons.</div>'+cfgField('brainResearchBridgeEnabled','Research Bridge aktiv','check','Erzeugt Analysebriefe ausschließlich aus vorhandener Telemetrie, Tagebuch, Lern- und Fehlerdaten.')+cfgField('brainResearchProfile','Standard-Analyse','select','',Object.keys(V214_RESEARCH_PROFILES).map(function(k){return [k,V214_RESEARCH_PROFILES[k].label];}))+cfgField('brainResearchHours','Analysefenster (Stunden)','number','1–168 Stunden.')+cfgField('brainResearchMaxHighlights','Max. relevante Highlights','number','5–40. Auffällige Rewards, Rollbacks, Qualitätswarnungen und Fehler werden priorisiert.')+cfgField('brainResearchAnonymize','Charakternamen anonymisieren','check','Ersetzt Namen im Export durch Merchant/Farmer1…; Secrets werden unabhängig davon immer entfernt.')+(summary?'<div class="line"><span>Bereit</span><strong>'+summary.repeatedErrors.length+' Fehlergruppen · '+summary.highlights.length+' Highlights</strong></div>':'')+'<div class="buttons"><button class="btn primary" data-action="research-copy" data-profile="'+esc(p)+'">Standard-Prompt kopieren</button><button class="btn" data-action="research-copy" data-profile="development">Entwicklungsbrief</button><button class="btn" data-action="research-copy" data-profile="errors">Fehleranalyse</button><button class="btn" data-action="research-show" data-profile="overall">Gesamtanalyse anzeigen</button></div></div>';};
  var v214UiClickBase=uiClick;
  uiClick=function(e){var t=e.target&&e.target.closest?e.target.closest('button'):null;if(t&&t.dataset&&t.dataset.action==='research-copy'){v214ResearchCopy(t.dataset.profile||C.brainResearchProfile);return;}if(t&&t.dataset&&t.dataset.action==='research-show'){v214ResearchShow(t.dataset.profile||C.brainResearchProfile);return;}return v214UiClickBase(e);};
  CSS+=' .research-bridge-card{border-color:color-mix(in srgb,#8c7cff 45%,var(--border))!important;box-shadow:inset 3px 0 0 color-mix(in srgb,#8c7cff 70%,var(--accent))}.research-prompt{width:100%;min-height:420px;resize:vertical;background:var(--panel2);color:var(--text);border:1px solid var(--line);border-radius:9px;padding:10px;font:10px/1.45 ui-monospace,SFMono-Regular,Menlo,monospace} ';

  var v210DashboardBase=dashboardPayload;
  dashboardPayload=function(){var d=v210DashboardBase();d.version=10;d.brain=v210BrainTelemetry();return d;};
  audit('feature_contract','2.14.0 Brain-v2 + Research Bridge Kernfunktionen geprüft',{features:FEATURE_CONTRACT,student:{inputs:V210_INPUTS,hidden:V210_HIDDEN,outputs:V210_OUTPUTS},configHash:v282ConfigHash(C)});'''
s=s.replace(marker,research,1)
# add debug functions
old="brainQuality:v213QualitySummary,brainQualityEvaluate:v213QualityEvaluate}};"
new="brainQuality:v213QualitySummary,brainQualityEvaluate:v213QualityEvaluate,brainResearchData:v214ResearchData,brainResearchPrompt:v214ResearchPrompt,brainResearchSummary:v214ResearchSummary}};"
assert old in s
s=s.replace(old,new,1)
# add whats new research card and tweak lead
s=s.replace("<b>Gehirn-Tagebuch</b><p class=\"muted\">Das Brain schreibt aus echten Teacher-Lektionen, Outcomes, Champion/Challenger-Ereignissen und Tageswechseln ein überprüfbares Lerntagebuch – ohne zusätzliche KI-Aufrufe.</p><button class=\"btn primary\" data-whats-open=\"brain\">Tagebuch ansehen</button></div>","<b>Gehirn-Tagebuch</b><p class=\"muted\">Das Brain schreibt aus echten Teacher-Lektionen, Outcomes, Champion/Challenger-Ereignissen und Tageswechseln ein überprüfbares Lerntagebuch – ohne zusätzliche KI-Aufrufe.</p><button class=\"btn primary\" data-whats-open=\"brain\">Tagebuch ansehen</button></div><div class=\"card\"><b>AiO Research Bridge</b><p class=\"muted\">Verdichtet Lern-, Reward-, Fehler-, Farm- und Merchant-Erfahrung in sichere ChatGPT-Analysebriefe mit optional anonymisierten Namen und strukturiertem JSON – ohne zusätzliche Workers-AI-Neurons.</p><button class=\"btn primary\" data-whats-open=\"brain\">Research Bridge ansehen</button></div>",1)
bot_path.write_text(s)

# bump metadata files
v=json.loads((root/'version.json').read_text())
v['version']='2.14.0';v['build']='2026-09-10';v['dashboardVersion']='2.14.0';v['dashboardPlatform']='cloudflare-workers-d1-ai-teacher-student-champion-challenger-diary-quality-research-bridge'
(root/'version.json').write_text(json.dumps(v,indent=2,ensure_ascii=False)+'\n')
pkg=json.loads((root/'cloudflare-dashboard/package.json').read_text());pkg['version']='2.14.0';(root/'cloudflare-dashboard/package.json').write_text(json.dumps(pkg,indent=2)+'\n')
