#!/usr/bin/env node
"use strict";

const fs = require("node:fs");
const path = require("node:path");

const ROOT = path.resolve(__dirname, "..");
const SRC = path.join(ROOT, "src");
const TEST = path.join(ROOT, "test");
const DOCS = path.join(ROOT, "docs");
const PACKAGE_FILE = path.join(ROOT, "package.json");
const CHECK_MODE = process.argv.includes("--check");

const CODE_EXTENSIONS = new Set([".js", ".cjs", ".mjs", ".ts", ".tsx"]);
const IGNORED_DIRECTORIES = new Set(["node_modules", "dist", "coverage", ".git"]);
const GENERATED_HEADER = "<!-- AUTO-GENERATED by scripts/generate-docs.js. DO NOT EDIT DIRECTLY. -->\n";

function toPosix(value) {
  return value.split(path.sep).join("/");
}

function relativeToRoot(file) {
  return toPosix(path.relative(ROOT, file));
}

function readText(file) {
  return fs.readFileSync(file, "utf8").replace(/\r\n/g, "\n");
}

function walkFiles(directory) {
  if (!fs.existsSync(directory)) return [];

  const result = [];
  const entries = fs.readdirSync(directory, { withFileTypes: true })
    .sort((a, b) => a.name.localeCompare(b.name, "en"));

  for (const entry of entries) {
    if (IGNORED_DIRECTORIES.has(entry.name)) continue;
    const fullPath = path.join(directory, entry.name);
    if (entry.isDirectory()) {
      result.push(...walkFiles(fullPath));
    } else if (entry.isFile()) {
      result.push(fullPath);
    }
  }
  return result;
}

function isCodeFile(file) {
  return CODE_EXTENSIONS.has(path.extname(file).toLowerCase());
}

function lineCount(text) {
  if (!text) return 0;
  const normalized = text.replace(/\n+$/, "");
  return normalized ? normalized.split("\n").length : 0;
}

function inlineCode(value) {
  const text = String(value);
  const fence = text.includes("`") ? "``" : "`";
  return `${fence}${text}${fence}`;
}

function tableCell(value) {
  return String(value).replace(/\|/g, "\\|").replace(/\n/g, " ");
}

function sourceGroupFromRelative(srcRelative) {
  const normalized = toPosix(srcRelative).replace(/^\.\//, "");
  const parts = normalized.split("/").filter(Boolean);
  return parts.length > 1 ? parts[0] : "(root)";
}

function compareAlphaDocsDescending(a, b) {
  function parts(file) {
    const match = path.basename(file).match(/^ALPHA_([0-9_]+)_COMPLETION\.md$/i);
    return match ? match[1].split("_").map(Number) : [];
  }
  const left = parts(a);
  const right = parts(b);
  const length = Math.max(left.length, right.length);
  for (let i = 0; i < length; i += 1) {
    const diff = (right[i] ?? -1) - (left[i] ?? -1);
    if (diff !== 0) return diff;
  }
  return path.basename(b).localeCompare(path.basename(a), "en");
}

function firstHeading(text, fallback) {
  const match = text.match(/^#\s+(.+)$/m);
  return match ? match[1].trim() : fallback;
}

function extractInternalDependencies(sourceFiles) {
  const edgeCounts = new Map();
  const patterns = [
    /\brequire\(\s*["'`]([^"'`]+)["'`]\s*\)/g,
    /\bfrom\s*["'`]([^"'`]+)["'`]/g,
    /\bimport\(\s*["'`]([^"'`]+)["'`]\s*\)/g,
  ];

  for (const file of sourceFiles) {
    const text = readText(file);
    const srcRelative = toPosix(path.relative(SRC, file));
    const sourceGroup = sourceGroupFromRelative(srcRelative);

    for (const pattern of patterns) {
      pattern.lastIndex = 0;
      let match;
      while ((match = pattern.exec(text)) !== null) {
        const specifier = match[1];
        if (!specifier.startsWith(".")) continue;

        const targetRelative = path.posix.normalize(
          path.posix.join(path.posix.dirname(srcRelative), specifier),
        );
        if (targetRelative === ".." || targetRelative.startsWith("../")) continue;
        const targetGroup = sourceGroupFromRelative(targetRelative);
        if (targetGroup === sourceGroup) continue;

        const key = `${sourceGroup}\u0000${targetGroup}`;
        edgeCounts.set(key, (edgeCounts.get(key) || 0) + 1);
      }
    }
  }

  return [...edgeCounts.entries()]
    .map(([key, count]) => {
      const [from, to] = key.split("\u0000");
      return { from, to, count };
    })
    .sort((a, b) => a.from.localeCompare(b.from, "en") || a.to.localeCompare(b.to, "en"));
}

function extractEnvironmentVariables(sourceFiles) {
  const variables = new Map();
  const patterns = [
    /\bprocess\.env\.([A-Za-z_][A-Za-z0-9_]*)/g,
    /\bprocess\.env\[\s*["']([^"']+)["']\s*\]/g,
  ];

  for (const file of sourceFiles) {
    const text = readText(file);
    for (const pattern of patterns) {
      pattern.lastIndex = 0;
      let match;
      while ((match = pattern.exec(text)) !== null) {
        if (!variables.has(match[1])) variables.set(match[1], new Set());
        variables.get(match[1]).add(relativeToRoot(file));
      }
    }
  }

  return [...variables.entries()]
    .map(([name, files]) => ({ name, files: [...files].sort() }))
    .sort((a, b) => a.name.localeCompare(b.name, "en"));
}

function extractEvents(sourceFiles) {
  const events = new Map();
  const pattern = /\.\s*(on|once|emit|trigger)\s*\(\s*["'`]([^"'`]+)["'`]/g;

  for (const file of sourceFiles) {
    const text = readText(file);
    pattern.lastIndex = 0;
    let match;
    while ((match = pattern.exec(text)) !== null) {
      const [, operation, name] = match;
      if (!events.has(name)) events.set(name, { operations: new Set(), files: new Set() });
      events.get(name).operations.add(operation);
      events.get(name).files.add(relativeToRoot(file));
    }
  }

  return [...events.entries()]
    .map(([name, data]) => ({
      name,
      operations: [...data.operations].sort(),
      files: [...data.files].sort(),
    }))
    .sort((a, b) => a.name.localeCompare(b.name, "en"));
}

function groupSourceFiles(sourceFiles) {
  const groups = new Map();
  for (const file of sourceFiles) {
    const srcRelative = toPosix(path.relative(SRC, file));
    const group = sourceGroupFromRelative(srcRelative);
    if (!groups.has(group)) groups.set(group, []);
    groups.get(group).push({
      path: `src/${srcRelative}`,
      lines: lineCount(readText(file)),
    });
  }

  return [...groups.entries()]
    .map(([name, files]) => ({
      name,
      files: files.sort((a, b) => a.path.localeCompare(b.path, "en")),
      lines: files.reduce((sum, file) => sum + file.lines, 0),
    }))
    .sort((a, b) => a.name.localeCompare(b.name, "en"));
}

function generatedReadme({ pkg, sourceGroups, sourceFiles, testFiles, alphaDocs }) {
  const totalSourceLines = sourceGroups.reduce((sum, group) => sum + group.lines, 0);
  return `${GENERATED_HEADER}
# Adventure Land AiO Bot v3

${pkg.description || "Adventure Land AiO Bot v3."}

**Version:** ${inlineCode(pkg.version)} · **Node.js:** ${inlineCode(pkg.engines?.node || "nicht angegeben")} · **Quellmodule:** ${sourceFiles.length} · **Tests:** ${testFiles.length} · **Source-Zeilen:** ${totalSourceLines}

> Diese Datei wird deterministisch aus dem Repository erzeugt. Technische Fakten sollten im Code oder in den Quelldateien geändert werden, nicht direkt hier.

## Schnellstart

\`\`\`bash
npm install
npm run build
npm test
npm run check
npm run docs:generate
\`\`\`

## Automatische Projektdokumentation

| Dokument | Inhalt |
| --- | --- |
| [ARCHITECTURE.md](docs/ARCHITECTURE.md) | Statische Struktur, Quellbereiche und interne Abhängigkeiten |
| [MODULES.md](docs/MODULES.md) | Inventar aller erkannten Source-Module mit Zeilenzahlen |
| [CONFIGURATION.md](docs/CONFIGURATION.md) | npm-Skripte, Umgebungsvariablen und config-nahe Dateien |
| [EVENTS.md](docs/EVENTS.md) | Statisch erkennbare Event-Literale und Fundstellen |
| [CHANGELOG-GENERATED.md](docs/CHANGELOG-GENERATED.md) | Index der vorhandenen Alpha-Abschlussdokumente |

## Projektüberblick

| Kennzahl | Wert |
| --- | ---: |
| Source-Dateien | ${sourceFiles.length} |
| Source-Zeilen | ${totalSourceLines} |
| Testdateien | ${testFiles.length} |
| Top-Level-Source-Bereiche | ${sourceGroups.length} |
| Alpha-Abschlussdokumente | ${alphaDocs.length} |

## Doku-Befehle

- ${inlineCode("npm run docs:generate")} aktualisiert alle generierten Dokumente lokal.
- ${inlineCode("npm run docs:check")} prüft nur, ob die generierten Dokumente aktuell sind, und verändert keine Dateien.

Die GitHub Action ${inlineCode("v3-documentation")} regeneriert die Dokumentation nach relevanten Änderungen auf ${inlineCode("main")} und committed ausschließlich die generierten Doku-Dateien.
`;
}

function generatedArchitecture({ sourceGroups, dependencies, sourceFiles }) {
  const entrypoints = sourceFiles
    .map((file) => toPosix(path.relative(SRC, file)))
    .filter((file) => !file.includes("/"))
    .sort();

  const groupRows = sourceGroups.length
    ? sourceGroups.map((group) => `| ${tableCell(group.name)} | ${group.files.length} | ${group.lines} |`).join("\n")
    : "| – | 0 | 0 |";

  const dependencyRows = dependencies.length
    ? dependencies.map((edge) => `| ${tableCell(edge.from)} | ${tableCell(edge.to)} | ${edge.count} |`).join("\n")
    : "| – | – | 0 |";

  return `${GENERATED_HEADER}
# Architektur – v3

Diese Sicht ist **statisch und syntaktisch**. Sie wird aus der aktuellen Struktur unter ${inlineCode("src/")} und aus relativen ${inlineCode("require/import")}‑Referenzen abgeleitet; dynamische Laufzeitbeziehungen können darüber hinausgehen.

## Source-Bereiche

| Bereich | Dateien | Codezeilen |
| --- | ---: | ---: |
${groupRows}

## Root-Entrypoints unter src/

${entrypoints.length ? entrypoints.map((file) => `- ${inlineCode(`src/${file}`)}`).join("\n") : "Keine Root-Entrypoints statisch erkannt."}

## Bereichsübergreifende interne Abhängigkeiten

| Von | Nach | statische Referenzen |
| --- | --- | ---: |
${dependencyRows}

## Interpretationsgrenze

Diese Datei beschreibt Struktur, nicht Verhalten. Zustandsautomaten, Event-Flows, dynamisch berechnete Importe oder Adventure-Land-Laufzeitobjekte sollten weiterhin über Code, Tests und Telemetrie validiert werden.
`;
}

function generatedModules({ sourceGroups }) {
  const sections = sourceGroups.map((group) => {
    const rows = group.files
      .map((file) => `| ${inlineCode(file.path)} | ${file.lines} |`)
      .join("\n");
    return `## ${group.name}\n\n**${group.files.length} Dateien · ${group.lines} Zeilen**\n\n| Datei | Zeilen |\n| --- | ---: |\n${rows}`;
  }).join("\n\n");

  return `${GENERATED_HEADER}
# Modul-Inventar – v3

Alle erkannten JavaScript-/TypeScript-Dateien unter ${inlineCode("src/")} werden nach ihrem ersten Verzeichnis gruppiert. Die Zeilenzahlen dienen als Größenindikator und sind keine Qualitätsmetrik.

${sections || "Keine Source-Module gefunden."}
`;
}

function generatedConfiguration({ pkg, environmentVariables, configFiles }) {
  const scripts = Object.entries(pkg.scripts || {}).sort(([a], [b]) => a.localeCompare(b, "en"));
  const scriptRows = scripts.length
    ? scripts.map(([name, command]) => `| ${inlineCode(name)} | ${inlineCode(command)} |`).join("\n")
    : "| – | – |";

  const envRows = environmentVariables.length
    ? environmentVariables.map((entry) => `| ${inlineCode(entry.name)} | ${entry.files.map(inlineCode).join(", ")} |`).join("\n")
    : "| – | Keine statisch erkannten process.env-Zugriffe |";

  const configRows = configFiles.length
    ? configFiles.map((file) => `| ${inlineCode(relativeToRoot(file))} | ${lineCount(readText(file))} |`).join("\n")
    : "| – | 0 |";

  return `${GENERATED_HEADER}
# Konfiguration – v3

Diese Datei inventarisiert statisch sichtbare Konfigurationsoberflächen. Sie ersetzt keine fachliche Beschreibung einzelner Optionen.

## package.json Scripts

| Script | Kommando |
| --- | --- |
${scriptRows}

## Erkannte Umgebungsvariablen

| Variable | Fundstellen |
| --- | --- |
${envRows}

## Config-nahe Source-Dateien

Erfasst werden Source-Dateien, deren Pfad Begriffe wie ${inlineCode("config")}, ${inlineCode("settings")}, ${inlineCode("options")} oder ${inlineCode("constants")} enthält.

| Datei | Zeilen |
| --- | ---: |
${configRows}
`;
}

function generatedEvents({ events }) {
  const rows = events.length
    ? events.map((event) => `| ${inlineCode(event.name)} | ${event.operations.map(inlineCode).join(", ")} | ${event.files.map(inlineCode).join(", ")} |`).join("\n")
    : "| – | – | Keine statisch erkannten Event-Literale |";

  return `${GENERATED_HEADER}
# Event-Inventar – v3

Erfasst werden String-Literale als erstes Argument von Aufrufen der Form ${inlineCode(".on(...)")}, ${inlineCode(".once(...)")}, ${inlineCode(".emit(...)")} und ${inlineCode(".trigger(...)")} in ${inlineCode("src/")}.

> Das ist bewusst nur ein statischer Index. Dynamische Event-Namen, Wrapper-Funktionen und implizite Adventure-Land-Events können fehlen.

| Event | Operationen | Fundstellen |
| --- | --- | --- |
${rows}
`;
}

function generatedChangelog({ pkg, alphaDocs }) {
  const rows = alphaDocs.length
    ? alphaDocs.map((file) => {
      const filename = path.basename(file);
      const title = firstHeading(readText(file), filename);
      return `| [${tableCell(filename)}](../${encodeURIComponent(filename)}) | ${tableCell(title)} |`;
    }).join("\n")
    : "| – | Keine Alpha-Abschlussdokumente gefunden |";

  return `${GENERATED_HEADER}
# Generierter Entwicklungsindex – v3

**Aktuelle Paketversion:** ${inlineCode(pkg.version)}

Dieser Index verlinkt die vorhandenen ${inlineCode("ALPHA_*_COMPLETION.md")}-Dokumente in absteigender Versionsreihenfolge. Er fasst deren Inhalte nicht neu zusammen und verändert die historischen Dateien nicht.

| Dokument | Titel |
| --- | --- |
${rows}
`;
}

function writeOrCheck(outputs) {
  const stale = [];
  for (const [target, content] of outputs) {
    const normalized = content.endsWith("\n") ? content : `${content}\n`;
    const exists = fs.existsSync(target);
    const current = exists ? readText(target) : null;

    if (current === normalized) continue;
    stale.push(relativeToRoot(target));
    if (!CHECK_MODE) {
      fs.mkdirSync(path.dirname(target), { recursive: true });
      fs.writeFileSync(target, normalized, "utf8");
      console.log(`updated ${relativeToRoot(target)}`);
    }
  }

  if (CHECK_MODE && stale.length) {
    console.error("Generated documentation is stale or missing:");
    for (const file of stale) console.error(`- ${file}`);
    process.exitCode = 1;
  } else if (CHECK_MODE) {
    console.log("Generated documentation is current.");
  } else if (!stale.length) {
    console.log("Generated documentation is already current.");
  }
}

function main() {
  const pkg = JSON.parse(readText(PACKAGE_FILE));
  const sourceFiles = walkFiles(SRC).filter(isCodeFile);
  const testFiles = walkFiles(TEST).filter(isCodeFile);
  const sourceGroups = groupSourceFiles(sourceFiles);
  const dependencies = extractInternalDependencies(sourceFiles);
  const environmentVariables = extractEnvironmentVariables(sourceFiles);
  const events = extractEvents(sourceFiles);
  const configFiles = sourceFiles.filter((file) => /(?:config|settings|options|constants)/i.test(relativeToRoot(file)));
  const alphaDocs = fs.readdirSync(ROOT, { withFileTypes: true })
    .filter((entry) => entry.isFile() && /^ALPHA_[0-9_]+_COMPLETION\.md$/i.test(entry.name))
    .map((entry) => path.join(ROOT, entry.name))
    .sort(compareAlphaDocsDescending);

  const context = {
    pkg,
    sourceFiles,
    testFiles,
    sourceGroups,
    dependencies,
    environmentVariables,
    events,
    configFiles,
    alphaDocs,
  };

  const outputs = [
    [path.join(ROOT, "README.md"), generatedReadme(context)],
    [path.join(DOCS, "ARCHITECTURE.md"), generatedArchitecture(context)],
    [path.join(DOCS, "MODULES.md"), generatedModules(context)],
    [path.join(DOCS, "CONFIGURATION.md"), generatedConfiguration(context)],
    [path.join(DOCS, "EVENTS.md"), generatedEvents(context)],
    [path.join(DOCS, "CHANGELOG-GENERATED.md"), generatedChangelog(context)],
  ];

  writeOrCheck(outputs);
}

main();
