local addonName, MG = ...
MG.SettingsSchema=MG.SettingsSchema or {}; local S=MG.SettingsSchema
S.categories={{id="general",labelKey="general",descriptionKey="general_desc"},{id="guides",labelKey="guides",descriptionKey="guides_desc"},{id="navigation",labelKey="navigation",descriptionKey="navigation_desc"},{id="automation",labelKey="automation",descriptionKey="automation_desc"},{id="gear",labelKey="gear",descriptionKey="gear_desc"},{id="trainer",labelKey="trainer",descriptionKey="trainer_desc"},{id="map",labelKey="map_markers",descriptionKey="map_desc"},{id="display",labelKey="display",descriptionKey="display_desc"},{id="audio",labelKey="audio",descriptionKey="audio_desc"},{id="data",labelKey="data_import",descriptionKey="data_desc"},{id="advanced",labelKey="advanced",descriptionKey="advanced_desc"}}
S.controls={
general={{type="language",key="language",labelKey="language"},{type="check",key="showMinimapButton",labelKey="minimap_button"},{type="check",key="showOnLogin",labelKey="show_on_login"},{type="check",key="compactMainWindow",labelKey="compact_main"},{type="check",key="tooltipsEnabled",labelKey="tooltips"},{type="check",key="characterProfiles",labelKey="character_profiles"}},
guides={{type="routeMode",key="routeMode",labelKey="route_mode"},{type="check",key="smartResync",labelKey="smart_resync"},{type="check",key="skipObsoleteSteps",labelKey="skip_obsolete"},{type="action",action="openGuides",labelKey="open_guides"}},
navigation={{type="check",key="showNavigator",labelKey="show_arrow"},{type="check",key="navigatorLocked",labelKey="navigator_locked"},{type="arrowSkin",key="navigatorArrowSkin",labelKey="style"},{type="scale",key="navigatorScale",labelKey="size"},{type="check",key="travelUseFlightPaths",labelKey="flight_paths"},{type="check",key="travelUseHearthstone",labelKey="hearthstone"},{type="check",key="travelUseTransports",labelKey="transports"},{type="check",key="travelUseClassTeleports",labelKey="class_teleports"},{type="check",key="travelPreferFastest",labelKey="fastest_route"},{type="check",key="travelSuggestAlternatives",labelKey="alt_routes"},{type="check",key="travelShowDetails",labelKey="detailed_travel"},{type="check",key="travelShowEstimatedTime",labelKey="estimated_time"},{type="check",key="travelMarkNextFlightMaster",labelKey="mark_next"},{type="check",key="travelHearthReminder",labelKey="hearth_reminder"},{type="check",key="travelShowAvailableTransport",labelKey="transport_available"},{type="action",action="resetNavigator",labelKey="reset_arrow"}},
automation={{type="check",key="autoAcceptQuests",labelKey="auto_accept"},{type="check",key="autoTurnInQuests",labelKey="auto_turnin"},{type="check",key="autoSelectSingleReward",labelKey="auto_single_reward"}},
gear={{type="check",key="gearAutoEquip",labelKey="auto_equip"},{type="check",key="gearSafeMode",labelKey="gear_safe"},{type="check",key="gearProtectBoE",labelKey="protect_boe"},{type="check",key="gearAutoEquipWeapons",labelKey="auto_weapons"},{type="check",key="gearRequireHighConfidence",labelKey="high_confidence"}},
trainer={{type="check",key="showTrainerHints",labelKey="trainer_hints"},{type="check",key="showTalentHints",labelKey="talent_hints"},{type="action",action="refreshTalent",labelKey="refresh_talent"}},
map={{type="check",key="showWorldMapMarker",labelKey="world_marker"},{type="check",key="autoSuperTrack",labelKey="auto_supertrack"},{type="check",key="showMinimapButton",labelKey="minimap_button"}},
display={{type="theme",key="theme",labelKey="theme"},{type="transparency",key="windowTransparency",labelKey="transparency"},{type="check",key="compactMainWindow",labelKey="compact_main"}},
audio={{type="check",key="audioEnabled",labelKey="audio_enabled"},{type="check",key="audioStepChange",labelKey="audio_step"},{type="check",key="audioAutoEquip",labelKey="audio_equip"}},
data={{type="info",key="dataStatus",labelKey="data_status"},{type="action",action="refreshData",labelKey="refresh_data"}},
advanced={{type="check",key="diagnostics",labelKey="diagnostics"},{type="check",key="telemetryLocal",labelKey="telemetry"},{type="action",action="openInfo",labelKey="open_info"},{type="action",action="resetSettings",labelKey="reset_all",danger=true}},
}
function S:GetCategories() return self.categories end
function S:GetControls(id) return self.controls[id] or {} end
function S:GetCategory(id) for _,c in ipairs(self.categories) do if c.id==id then return c end end return self.categories[1] end
